-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Blocks"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "SellerId" integer NOT NULL,
    "BlockedUserIds" integer[] NOT NULL,
    CONSTRAINT "PK_Blocks" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CartItems"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CartId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Carts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Conversations"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CourseId" integer NOT NULL,
    "BuyerId" integer NOT NULL,
    "SellerId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone NOT NULL,
    "IsVisible" boolean NOT NULL DEFAULT true,
    "IsBlock" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseContents"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseContents" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseSkills"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseSkills" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Courses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric NOT NULL,
    "Level" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TeacherName" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "ImageUrl" text COLLATE pg_catalog."default",
    "DurationHours" integer NOT NULL,
    "TotalPurchased" integer NOT NULL,
    "AverageRating" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SellerId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsApproved" boolean NOT NULL DEFAULT false,
    "IsRestricted" boolean NOT NULL DEFAULT false,
    "CourseLecture" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Enrollments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EnrollAt" timestamp with time zone NOT NULL,
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Favorites"
(
    "UserId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE IF NOT EXISTS public."Histories"
(
    "UserId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_Histories" PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE IF NOT EXISTS public."Messages"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "ConversationId" integer NOT NULL,
    "SenderId" integer NOT NULL,
    "Content" text COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Message" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "SellerId" integer NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Reviews"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Star" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Comment" text COLLATE pg_catalog."default",
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TargetLearners"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TargetLearners" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TransactionDetails"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" numeric NOT NULL,
    "TransactionId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TransactionDetails" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TransactionCode" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PaymentMethod" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "BuyerId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FullName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RefreshToken" character varying(500) COLLATE pg_catalog."default",
    "RefreshTokenExpiryTime" timestamp with time zone,
    "PhoneNumber" character varying(15) COLLATE pg_catalog."default",
    "EmailVerificationToken" character varying(200) COLLATE pg_catalog."default",
    "EmailVerificationTokenExpiry" timestamp with time zone,
    "IsEmailVerified" boolean NOT NULL DEFAULT false,
    "PasswordResetToken" character varying(200) COLLATE pg_catalog."default",
    "PasswordResetTokenExpiry" timestamp with time zone,
    "AvatarUrl" character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Blocks"
    ADD CONSTRAINT "FK_Blocks_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Blocks_SellerId"
    ON public."Blocks"("SellerId");


ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId")
    REFERENCES public."Carts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CartId"
    ON public."CartItems"("CartId");


ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CourseId"
    ON public."CartItems"("CourseId");


ALTER TABLE IF EXISTS public."Carts"
    ADD CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Carts_UserId"
    ON public."Carts"("UserId");


ALTER TABLE IF EXISTS public."Conversations"
    ADD CONSTRAINT "FK_Conversations_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Conversations_CourseId"
    ON public."Conversations"("CourseId");


ALTER TABLE IF EXISTS public."Conversations"
    ADD CONSTRAINT "FK_Conversations_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Conversations_BuyerId"
    ON public."Conversations"("BuyerId");


ALTER TABLE IF EXISTS public."Conversations"
    ADD CONSTRAINT "FK_Conversations_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Conversations_SellerId"
    ON public."Conversations"("SellerId");


ALTER TABLE IF EXISTS public."CourseContents"
    ADD CONSTRAINT "FK_CourseContents_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseContents_CourseId"
    ON public."CourseContents"("CourseId");


ALTER TABLE IF EXISTS public."CourseSkills"
    ADD CONSTRAINT "FK_CourseSkills_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseSkills_CourseId"
    ON public."CourseSkills"("CourseId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Categories_CategoryId" FOREIGN KEY ("CategoryId")
    REFERENCES public."Categories" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_CategoryId"
    ON public."Courses"("CategoryId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_SellerId"
    ON public."Courses"("SellerId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_CourseId"
    ON public."Enrollments"("CourseId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_BuyerId"
    ON public."Enrollments"("BuyerId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Favorites_CourseId"
    ON public."Favorites"("CourseId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Histories"
    ADD CONSTRAINT "FK_Histories_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Histories_CourseId"
    ON public."Histories"("CourseId");


ALTER TABLE IF EXISTS public."Histories"
    ADD CONSTRAINT "FK_Histories_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Messages"
    ADD CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId")
    REFERENCES public."Conversations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Messages_ConversationId"
    ON public."Messages"("ConversationId");


ALTER TABLE IF EXISTS public."Messages"
    ADD CONSTRAINT "FK_Messages_Users_SenderId" FOREIGN KEY ("SenderId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Messages_SenderId"
    ON public."Messages"("SenderId");


ALTER TABLE IF EXISTS public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Notifications_SellerId"
    ON public."Notifications"("SellerId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_CourseId"
    ON public."Reviews"("CourseId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_BuyerId"
    ON public."Reviews"("BuyerId");


ALTER TABLE IF EXISTS public."TargetLearners"
    ADD CONSTRAINT "FK_TargetLearners_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TargetLearners_CourseId"
    ON public."TargetLearners"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_CourseId"
    ON public."TransactionDetails"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Transactions_TransactionId" FOREIGN KEY ("TransactionId")
    REFERENCES public."Transactions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_TransactionId"
    ON public."TransactionDetails"("TransactionId");


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Transactions_BuyerId"
    ON public."Transactions"("BuyerId");

END;




-- I. Tạo function để tự động tăng TotalPurchased
CREATE OR REPLACE FUNCTION increase_total_purchased()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public."Courses"
    SET "TotalPurchased" = "TotalPurchased" + 1
    WHERE "Id" = NEW."CourseId";
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Gắn trigger vào bảng Enrollments
CREATE TRIGGER trg_increase_total_purchased
AFTER INSERT ON public."Enrollments"
FOR EACH ROW
EXECUTE FUNCTION increase_total_purchased();


-- II. Tạo function để tính lại AverageRating
CREATE OR REPLACE FUNCTION update_course_average_rating()
RETURNS TRIGGER AS $$
DECLARE
    course_id_to_update INTEGER;
    new_avg_rating NUMERIC;
BEGIN
    -- Xác định CourseId cần update (tùy theo INSERT, UPDATE, DELETE)
    IF (TG_OP = 'DELETE') THEN
        course_id_to_update := OLD."CourseId";
    ELSE
        course_id_to_update := NEW."CourseId";
    END IF;

    -- Tính lại AverageRating từ bảng Reviews
    SELECT COALESCE(AVG("Star"), 0)
    INTO new_avg_rating
    FROM public."Reviews"
    WHERE "CourseId" = course_id_to_update;

    -- Cập nhật AverageRating vào bảng Courses
    UPDATE public."Courses"
    SET "AverageRating" = ROUND(new_avg_rating, 2),
        "UpdatedAt" = NOW()
    WHERE "Id" = course_id_to_update;

    -- Trả về giá trị phù hợp
    IF (TG_OP = 'DELETE') THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 1. Tạo trigger khi INSERT review mới
CREATE TRIGGER trigger_insert_review_update_rating
AFTER INSERT ON public."Reviews"
FOR EACH ROW
EXECUTE FUNCTION update_course_average_rating();

-- 2. Tạo trigger khi UPDATE review (thay đổi Star)
CREATE TRIGGER trigger_update_review_update_rating
AFTER UPDATE OF "Star" ON public."Reviews"
FOR EACH ROW
WHEN (OLD."Star" IS DISTINCT FROM NEW."Star")
EXECUTE FUNCTION update_course_average_rating();

-- 3. Tạo trigger khi DELETE review
CREATE TRIGGER trigger_delete_review_update_rating
AFTER DELETE ON public."Reviews"
FOR EACH ROW
EXECUTE FUNCTION update_course_average_rating();

-- Trigger để insert Enrollment
CREATE OR REPLACE FUNCTION fn_create_enrollment_from_transactiondetail()
RETURNS TRIGGER AS $$
DECLARE
    trans_record RECORD;
BEGIN
    -- Lấy thông tin giao dịch từ bảng Transactions
    SELECT "BuyerId", "CreatedAt"
    INTO trans_record
    FROM public."Transactions"
    WHERE "Id" = NEW."TransactionId";

    -- Chèn vào bảng Enrollments
    INSERT INTO public."Enrollments" ("EnrollAt", "BuyerId", "CourseId")
    VALUES (trans_record."CreatedAt", trans_record."BuyerId", NEW."CourseId");

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_create_enrollment_on_transactiondetail
AFTER INSERT ON public."TransactionDetails"
FOR EACH ROW
EXECUTE FUNCTION fn_create_enrollment_from_transactiondetail();


