-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."CartItems"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CartId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Carts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT '-infinity'::timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseContents"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseContents" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseSkills"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseSkills" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Courses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric NOT NULL,
    "Level" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TeacherName" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "ImageUrl" text COLLATE pg_catalog."default",
    "DurationHours" integer NOT NULL,
    "TotalPurchased" integer NOT NULL,
    "AverageRating" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SellerId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsApproved" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Enrollments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EnrollAt" timestamp with time zone NOT NULL,
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Favorites"
(
    "UserId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("UserId", "CourseId")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Message" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "SellerId" integer NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Reviews"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Star" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Comment" text COLLATE pg_catalog."default",
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TargetLearners"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TargetLearners" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TransactionDetails"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" numeric NOT NULL,
    "TransactionId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TransactionDetails" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TransactionCode" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PaymentMethod" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "BuyerId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FullName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RefreshToken" character varying(500) COLLATE pg_catalog."default",
    "RefreshTokenExpiryTime" timestamp with time zone,
    "PhoneNumber" character varying(15) COLLATE pg_catalog."default",
    "EmailVerificationToken" character varying(200) COLLATE pg_catalog."default",
    "EmailVerificationTokenExpiry" timestamp with time zone,
    "IsEmailVerified" boolean NOT NULL DEFAULT false,
    "PasswordResetToken" character varying(200) COLLATE pg_catalog."default",
    "PasswordResetTokenExpiry" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId")
    REFERENCES public."Carts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CartId"
    ON public."CartItems"("CartId");


ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CourseId"
    ON public."CartItems"("CourseId");


ALTER TABLE IF EXISTS public."Carts"
    ADD CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Carts_UserId"
    ON public."Carts"("UserId");


ALTER TABLE IF EXISTS public."CourseContents"
    ADD CONSTRAINT "FK_CourseContents_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseContents_CourseId"
    ON public."CourseContents"("CourseId");


ALTER TABLE IF EXISTS public."CourseSkills"
    ADD CONSTRAINT "FK_CourseSkills_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseSkills_CourseId"
    ON public."CourseSkills"("CourseId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Categories_CategoryId" FOREIGN KEY ("CategoryId")
    REFERENCES public."Categories" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_CategoryId"
    ON public."Courses"("CategoryId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_SellerId"
    ON public."Courses"("SellerId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_CourseId"
    ON public."Enrollments"("CourseId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_BuyerId"
    ON public."Enrollments"("BuyerId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Favorites_CourseId"
    ON public."Favorites"("CourseId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Notifications_SellerId"
    ON public."Notifications"("SellerId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_CourseId"
    ON public."Reviews"("CourseId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_BuyerId"
    ON public."Reviews"("BuyerId");


ALTER TABLE IF EXISTS public."TargetLearners"
    ADD CONSTRAINT "FK_TargetLearners_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TargetLearners_CourseId"
    ON public."TargetLearners"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_CourseId"
    ON public."TransactionDetails"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Transactions_TransactionId" FOREIGN KEY ("TransactionId")
    REFERENCES public."Transactions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_TransactionId"
    ON public."TransactionDetails"("TransactionId");


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Transactions_BuyerId"
    ON public."Transactions"("BuyerId");

END;

-- =====================================================
-- INSERT USERS (Người dùng)
-- =====================================================
INSERT INTO public."Users" 
("FullName", "Email", "PasswordHash", "Role", "CreatedAt", "PhoneNumber", "IsEmailVerified", "RefreshToken", "RefreshTokenExpiryTime")
VALUES
-- Admin (Email đã xác nhận)
('Nguyễn Văn Admin', 'admin@coursehub.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Admin', NOW() - INTERVAL '365 days', '0901234567', true, NULL, NULL),

-- Sellers (Giáo viên - một số đã xác nhận, một số chưa)
('Trần Thị Hoa', 'hoa.tran@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', NOW() - INTERVAL '200 days', '0912345678', true, NULL, NULL),
('Lê Văn Minh', 'minh.le@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', NOW() - INTERVAL '180 days', '0923456789', false, NULL, NULL),
('Phạm Thị Lan', 'lan.pham@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', NOW() - INTERVAL '150 days', '0934567890', true, NULL, NULL),
('Hoàng Văn Nam', 'nam.hoang@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', NOW() - INTERVAL '120 days', '0945678901', true, NULL, NULL),

-- Buyers (Học viên - một số đã xác nhận, một số chưa)
('Đỗ Văn Hùng', 'hung.do@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '100 days', '0956789012', true, NULL, NULL),
('Vũ Thị Mai', 'mai.vu@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '90 days', '0967890123', false, NULL, NULL),
('Bùi Văn Tuấn', 'tuan.bui@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '80 days', '0978901234', true, NULL, NULL),
('Đinh Thị Hương', 'huong.dinh@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '70 days', '0989012345', true, NULL, NULL),
('Ngô Văn Long', 'long.ngo@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '60 days', '0990123456', false, NULL, NULL),
('Trương Thị Thu', 'thu.truong@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', NOW() - INTERVAL '50 days', '0901234568', true, NULL, NULL);

-- =====================================================
-- INSERT CATEGORIES (Danh mục khóa học)
-- =====================================================
INSERT INTO public."Categories" ("Name", "CreatedAt")
VALUES
('Lập trình Web', NOW() - INTERVAL '400 days'),
('Lập trình Mobile', NOW() - INTERVAL '390 days'),
('Data Science', NOW() - INTERVAL '380 days'),
('Thiết kế đồ họa', NOW() - INTERVAL '370 days'),
('Marketing Digital', NOW() - INTERVAL '360 days'),
('Kinh doanh', NOW() - INTERVAL '350 days'),
('Ngoại ngữ', NOW() - INTERVAL '340 days'),
('Phát triển cá nhân', NOW() - INTERVAL '330 days');

-- =====================================================
-- INSERT COURSES (Khóa học)
-- =====================================================
INSERT INTO public."Courses" 
("Title", "Description", "Price", "Level", "TeacherName", "ImageUrl", "DurationHours", "TotalPurchased", "AverageRating", "CreatedAt", "UpdatedAt", "SellerId", "CategoryId", "IsApproved")
VALUES
-- Khóa học đã được duyệt
('Lập trình React từ cơ bản đến nâng cao', 'Khóa học giúp bạn nắm vững React, từ JSX, Components đến Hooks và Redux. Phù hợp cho người mới bắt đầu.', 1500000, 'Beginner', 'Trần Thị Hoa', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee', 40, 150, 4.8, NOW() - INTERVAL '180 days', NOW() - INTERVAL '10 days', 2, 1, true),

('Python cho Data Science', 'Học Python từ đầu, pandas, numpy, matplotlib và các thuật toán Machine Learning cơ bản.', 2000000, 'Intermediate', 'Phạm Thị Lan', 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935', 50, 200, 4.9, NOW() - INTERVAL '150 days', NOW() - INTERVAL '5 days', 4, 3, true),

('Flutter - Xây dựng ứng dụng di động đa nền tảng', 'Khóa học Flutter giúp bạn tạo ứng dụng iOS và Android từ một mã nguồn duy nhất.', 1800000, 'Beginner', 'Hoàng Văn Nam', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c', 45, 120, 4.7, NOW() - INTERVAL '120 days', NOW() - INTERVAL '8 days', 5, 2, true),

('Adobe Photoshop cho người mới bắt đầu', 'Khóa học Photoshop từ A-Z, thiết kế banner, poster, chỉnh sửa ảnh chuyên nghiệp.', 1200000, 'Beginner', 'Trần Thị Hoa', 'https://images.unsplash.com/photo-1626785774573-4b799315345d', 30, 180, 4.6, NOW() - INTERVAL '100 days', NOW() - INTERVAL '12 days', 2, 4, true),

('Marketing trên Facebook & Instagram', 'Chiến lược marketing hiệu quả trên mạng xã hội, chạy quảng cáo Facebook Ads và Instagram Ads.', 1000000, 'Beginner', 'Lê Văn Minh', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113', 25, 250, 4.5, NOW() - INTERVAL '90 days', NOW() - INTERVAL '15 days', 3, 5, true),

-- Khóa học chưa được duyệt
('Node.js và Express - Backend Development', 'Xây dựng RESTful API với Node.js, Express, MongoDB. Tích hợp JWT authentication.', 1700000, 'Intermediate', 'Lê Văn Minh', 'https://images.unsplash.com/photo-1627398242454-45a1465c2479', 38, 0, 0, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days', 3, 1, false),

('Tiếng Anh giao tiếp cơ bản', 'Học tiếng Anh giao tiếp hàng ngày, phát âm chuẩn, từ vựng thực tế.', 800000, 'Beginner', 'Phạm Thị Lan', 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d', 35, 0, 0, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days', 4, 7, false),

('Quản trị doanh nghiệp hiện đại', 'Các kỹ năng quản lý, lãnh đạo, xây dựng đội nhóm và phát triển doanh nghiệp bền vững.', 2500000, 'Advanced', 'Hoàng Văn Nam', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40', 60, 0, 0, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days', 5, 6, false);

-- =====================================================
-- INSERT COURSE CONTENTS (Nội dung khóa học)
-- =====================================================
INSERT INTO public."CourseContents" ("Title", "Description", "CourseId")
VALUES
-- Course 1: React
('Giới thiệu về React', 'Tổng quan về React, JSX và Virtual DOM', 1),
('Components và Props', 'Cách tạo và sử dụng components, truyền props', 1),
('State và Lifecycle', 'Quản lý state, lifecycle methods trong React', 1),
('React Hooks', 'useState, useEffect, useContext và custom hooks', 1),
('Redux cơ bản', 'State management với Redux', 1),

-- Course 2: Python Data Science
('Python cơ bản', 'Cú pháp Python, biến, vòng lặp, hàm', 2),
('Pandas và NumPy', 'Xử lý dữ liệu với Pandas và NumPy', 2),
('Visualization với Matplotlib', 'Vẽ biểu đồ và trực quan hóa dữ liệu', 2),
('Machine Learning cơ bản', 'Thuật toán Linear Regression, Decision Tree', 2),

-- Course 3: Flutter
('Dart programming', 'Ngôn ngữ Dart cơ bản cho Flutter', 3),
('Flutter Widgets', 'StatelessWidget, StatefulWidget, Material Design', 3),
('Navigation và Routing', 'Điều hướng giữa các màn hình', 3),
('State Management', 'Provider, Bloc pattern trong Flutter', 3),

-- Course 4: Photoshop
('Giao diện Photoshop', 'Làm quen với workspace và tools', 4),
('Layers và Masks', 'Làm việc với layers, layer masks', 4),
('Retouching ảnh', 'Chỉnh sửa và làm đẹp ảnh', 4),

-- Course 5: Marketing
('Facebook Marketing Overview', 'Giới thiệu về Facebook Marketing', 5),
('Tạo Facebook Ads', 'Cách tạo và tối ưu quảng cáo Facebook', 5),
('Instagram Marketing', 'Chiến lược marketing trên Instagram', 5);

-- =====================================================
-- INSERT COURSE SKILLS (Kỹ năng học được)
-- =====================================================
INSERT INTO public."CourseSkills" ("Name", "CourseId")
VALUES
-- Course 1
('React.js', 1), ('JavaScript ES6+', 1), ('Redux', 1), ('React Hooks', 1),
-- Course 2
('Python', 2), ('Pandas', 2), ('Machine Learning', 2), ('Data Visualization', 2),
-- Course 3
('Flutter', 3), ('Dart', 3), ('Mobile Development', 3), ('UI/UX Design', 3),
-- Course 4
('Photoshop', 4), ('Graphic Design', 4), ('Photo Editing', 4),
-- Course 5
('Facebook Ads', 5), ('Social Media Marketing', 5), ('Content Marketing', 5);

-- =====================================================
-- INSERT TARGET LEARNERS (Đối tượng học viên)
-- =====================================================
INSERT INTO public."TargetLearners" ("Description", "CourseId")
VALUES
-- Course 1
('Người mới bắt đầu học lập trình web', 1),
('Lập trình viên muốn học React', 1),
('Sinh viên công nghệ thông tin', 1),

-- Course 2
('Người quan tâm đến Data Science', 2),
('Lập trình viên muốn chuyển sang AI/ML', 2),
('Nhà phân tích dữ liệu', 2),

-- Course 3
('Lập trình viên muốn làm mobile app', 3),
('Người mới bắt đầu với Flutter', 3),

-- Course 4
('Người yêu thích thiết kế đồ họa', 4),
('Nhân viên marketing cần thiết kế', 4),

-- Course 5
('Chủ doanh nghiệp nhỏ', 5),
('Nhân viên marketing', 5),
('Freelancer cần học marketing online', 5);

-- =====================================================
-- INSERT ENROLLMENTS (Đăng ký khóa học)
-- =====================================================
INSERT INTO public."Enrollments" ("EnrollAt", "BuyerId", "CourseId")
VALUES
-- User 6 (Đỗ Văn Hùng)
(NOW() - INTERVAL '95 days', 6, 1),
(NOW() - INTERVAL '90 days', 6, 2),

-- User 7 (Vũ Thị Mai)
(NOW() - INTERVAL '85 days', 7, 1),
(NOW() - INTERVAL '80 days', 7, 4),

-- User 8 (Bùi Văn Tuấn)
(NOW() - INTERVAL '75 days', 8, 2),
(NOW() - INTERVAL '70 days', 8, 3),
(NOW() - INTERVAL '65 days', 8, 5),

-- User 9 (Đinh Thị Hương)
(NOW() - INTERVAL '60 days', 9, 1),
(NOW() - INTERVAL '55 days', 9, 5),

-- User 10 (Ngô Văn Long)
(NOW() - INTERVAL '50 days', 10, 4),

-- User 11 (Trương Thị Thu)
(NOW() - INTERVAL '45 days', 11, 2),
(NOW() - INTERVAL '40 days', 11, 3);

-- =====================================================
-- INSERT REVIEWS (Đánh giá khóa học)
-- =====================================================
INSERT INTO public."Reviews" ("Star", "CreatedAt", "Comment", "BuyerId", "CourseId")
VALUES
-- Course 1
(5, NOW() - INTERVAL '90 days', 'Khóa học rất hay, giảng viên nhiệt tình. Tôi đã học được rất nhiều về React!', 6, 1),
(5, NOW() - INTERVAL '82 days', 'Nội dung dễ hiểu, ví dụ thực tế. Rất đáng để học!', 7, 1),
(4, NOW() - INTERVAL '58 days', 'Khóa học tốt nhưng cần thêm nhiều bài tập thực hành hơn.', 9, 1),

-- Course 2
(5, NOW() - INTERVAL '88 days', 'Khóa học Python tuyệt vời! Từ cơ bản đến nâng cao đều rất chi tiết.', 6, 2),
(5, NOW() - INTERVAL '72 days', 'Giảng viên giỏi, kiến thức chắc chắn. Rất hài lòng!', 8, 2),
(5, NOW() - INTERVAL '43 days', 'Best course về Data Science mà tôi từng học.', 11, 2),

-- Course 3
(5, NOW() - INTERVAL '68 days', 'Flutter rất thú vị, học xong có thể làm app luôn.', 8, 3),
(4, NOW() - INTERVAL '38 days', 'Khóa học hay nhưng hơi nhanh một chút.', 11, 3),

-- Course 4
(4, NOW() - INTERVAL '78 days', 'Học Photoshop hiệu quả, giờ tôi có thể tự thiết kế được rồi.', 7, 4),
(5, NOW() - INTERVAL '48 days', 'Giảng viên dạy rất dễ hiểu, không bị khó như tôi nghĩ.', 10, 4),

-- Course 5
(4, NOW() - INTERVAL '63 days', 'Khóa học marketing thực chiến, áp dụng được ngay.', 8, 5),
(5, NOW() - INTERVAL '53 days', 'Rất hữu ích cho công việc của tôi. Recommend!', 9, 5);

-- =====================================================
-- INSERT FAVORITES (Yêu thích khóa học)
-- =====================================================
INSERT INTO public."Favorites" ("UserId", "CourseId")
VALUES
(6, 3), (6, 4), (6, 5),
(7, 2), (7, 3), (7, 5),
(8, 1), (8, 4),
(9, 2), (9, 3), (9, 4),
(10, 1), (10, 2), (10, 3),
(11, 1), (11, 4), (11, 5);

-- =====================================================
-- INSERT CARTS (Giỏ hàng)
-- =====================================================
INSERT INTO public."Carts" ("UserId", "CreatedAt")
VALUES
(6, NOW() - INTERVAL '5 days'),
(7, NOW() - INTERVAL '3 days'),
(10, NOW() - INTERVAL '2 days');

-- =====================================================
-- INSERT CART ITEMS (Sản phẩm trong giỏ hàng)
-- =====================================================
INSERT INTO public."CartItems" ("CartId", "CourseId")
VALUES
-- Cart của User 6
(1, 3),
(1, 5),

-- Cart của User 7
(2, 2),
(2, 3),

-- Cart của User 10
(3, 1),
(3, 2),
(3, 5);

-- =====================================================
-- INSERT TRANSACTIONS (Giao dịch)
-- =====================================================
INSERT INTO public."Transactions" 
("TransactionCode", "PaymentMethod", "TotalAmount", "CreatedAt", "UpdatedAt", "BuyerId")
VALUES
('TXN001-2024-001', 'VNPay', 3500000, NOW() - INTERVAL '95 days', NOW() - INTERVAL '95 days', 6),
('TXN001-2024-002', 'MoMo', 1500000, NOW() - INTERVAL '85 days', NOW() - INTERVAL '85 days', 7),
('TXN001-2024-003', 'Banking', 1200000, NOW() - INTERVAL '80 days', NOW() - INTERVAL '80 days', 7),
('TXN001-2024-004', 'VNPay', 5500000, NOW() - INTERVAL '75 days', NOW() - INTERVAL '75 days', 8),
('TXN001-2024-005', 'MoMo', 2500000, NOW() - INTERVAL '60 days', NOW() - INTERVAL '60 days', 9),
('TXN001-2024-006', 'Banking', 1200000, NOW() - INTERVAL '50 days', NOW() - INTERVAL '50 days', 10),
('TXN001-2024-007', 'VNPay', 3800000, NOW() - INTERVAL '45 days', NOW() - INTERVAL '45 days', 11);

-- =====================================================
-- INSERT TRANSACTION DETAILS (Chi tiết giao dịch)
-- =====================================================
INSERT INTO public."TransactionDetails" ("Price", "TransactionId", "CourseId")
VALUES
-- Transaction 1 (User 6 mua 2 khóa học)
(1500000, 1, 1),
(2000000, 1, 2),

-- Transaction 2 (User 7 mua 1 khóa học)
(1500000, 2, 1),

-- Transaction 3 (User 7 mua 1 khóa học)
(1200000, 3, 4),

-- Transaction 4 (User 8 mua 3 khóa học)
(2000000, 4, 2),
(1800000, 4, 3),
(1700000, 4, 5),

-- Transaction 5 (User 9 mua 2 khóa học)
(1500000, 5, 1),
(1000000, 5, 5),

-- Transaction 6 (User 10 mua 1 khóa học)
(1200000, 6, 4),

-- Transaction 7 (User 11 mua 2 khóa học)
(2000000, 7, 2),
(1800000, 7, 3);

-- =====================================================
-- INSERT NOTIFICATIONS (Thông báo cho Seller)
-- =====================================================
INSERT INTO public."Notifications" 
("Message", "CreatedAt", "IsRead", "SellerId")
VALUES
-- Notifications for Seller 2 (Trần Thị Hoa)
('Bạn có đơn hàng mới từ khóa học "Lập trình React từ cơ bản đến nâng cao"', NOW() - INTERVAL '95 days', true, 2),
('Học viên Vũ Thị Mai đã đăng ký khóa học của bạn', NOW() - INTERVAL '85 days', true, 2),
('Bạn nhận được đánh giá 5 sao cho khóa học React', NOW() - INTERVAL '90 days', true, 2),
('Khóa học "Adobe Photoshop cho người mới bắt đầu" đã được duyệt', NOW() - INTERVAL '100 days', true, 2),

-- Notifications for Seller 3 (Lê Văn Minh)
('Khóa học "Marketing trên Facebook & Instagram" đã được duyệt', NOW() - INTERVAL '90 days', true, 3),
('Bạn có khóa học đang chờ duyệt: Node.js và Express', NOW() - INTERVAL '30 days', false, 3),

-- Notifications for Seller 4 (Phạm Thị Lan)
('Khóa học "Python cho Data Science" được 200 học viên đăng ký', NOW() - INTERVAL '50 days', true, 4),
('Bạn nhận được đánh giá 5 sao từ học viên', NOW() - INTERVAL '88 days', true, 4),
('Khóa học "Tiếng Anh giao tiếp cơ bản" đang chờ duyệt', NOW() - INTERVAL '20 days', false, 4),

-- Notifications for Seller 5 (Hoàng Văn Nam)
('Khóa học Flutter đã có 120 học viên đăng ký', NOW() - INTERVAL '60 days', true, 5),
('Bạn có khóa học mới đang chờ duyệt', NOW() - INTERVAL '15 days', false, 5);


-- 1. Tạo function để tính lại AverageRating
CREATE OR REPLACE FUNCTION update_course_average_rating()
RETURNS TRIGGER AS $$
DECLARE
    course_id_to_update INTEGER;
    new_avg_rating NUMERIC;
BEGIN
    -- Xác định CourseId cần update (tùy theo INSERT, UPDATE, DELETE)
    IF (TG_OP = 'DELETE') THEN
        course_id_to_update := OLD."CourseId";
    ELSE
        course_id_to_update := NEW."CourseId";
    END IF;

    -- Tính lại AverageRating từ bảng Reviews
    SELECT COALESCE(AVG("Star"), 0)
    INTO new_avg_rating
    FROM public."Reviews"
    WHERE "CourseId" = course_id_to_update;

    -- Cập nhật AverageRating vào bảng Courses
    UPDATE public."Courses"
    SET "AverageRating" = ROUND(new_avg_rating, 2),
        "UpdatedAt" = NOW()
    WHERE "Id" = course_id_to_update;

    -- Trả về giá trị phù hợp
    IF (TG_OP = 'DELETE') THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- 2. Tạo trigger khi INSERT review mới
CREATE TRIGGER trigger_insert_review_update_rating
AFTER INSERT ON public."Reviews"
FOR EACH ROW
EXECUTE FUNCTION update_course_average_rating();

-- 3. Tạo trigger khi UPDATE review (thay đổi Star)
CREATE TRIGGER trigger_update_review_update_rating
AFTER UPDATE OF "Star" ON public."Reviews"
FOR EACH ROW
WHEN (OLD."Star" IS DISTINCT FROM NEW."Star")
EXECUTE FUNCTION update_course_average_rating();

-- 4. Tạo trigger khi DELETE review
CREATE TRIGGER trigger_delete_review_update_rating
AFTER DELETE ON public."Reviews"
FOR EACH ROW
EXECUTE FUNCTION update_course_average_rating();