-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."CartItems"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "CartId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Carts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseContents"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseContents" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CourseSkills"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_CourseSkills" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Courses"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Price" numeric NOT NULL,
    "Level" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TeacherName" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "ImageUrl" text COLLATE pg_catalog."default",
    "DurationHours" integer NOT NULL,
    "TotalPurchased" integer NOT NULL,
    "AverageRating" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SellerId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "IsApproved" boolean NOT NULL DEFAULT false,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Enrollments"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "EnrollAt" timestamp with time zone NOT NULL,
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Favorites"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Favorites" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Message" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRead" boolean NOT NULL,
    "SellerId" integer NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Reviews"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Star" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Comment" text COLLATE pg_catalog."default",
    "BuyerId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TargetLearners"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Description" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TargetLearners" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TransactionDetails"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" numeric NOT NULL,
    "TransactionId" integer NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_TransactionDetails" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Transactions"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "TransactionCode" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "PaymentMethod" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "BuyerId" integer NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FullName" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Email" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default" NOT NULL,
    "Role" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RefreshToken" character varying(500) COLLATE pg_catalog."default",
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId")
    REFERENCES public."Carts" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CartId"
    ON public."CartItems"("CartId");


ALTER TABLE IF EXISTS public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CartItems_CourseId"
    ON public."CartItems"("CourseId");


ALTER TABLE IF EXISTS public."Carts"
    ADD CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Carts_UserId"
    ON public."Carts"("UserId");


ALTER TABLE IF EXISTS public."CourseContents"
    ADD CONSTRAINT "FK_CourseContents_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseContents_CourseId"
    ON public."CourseContents"("CourseId");


ALTER TABLE IF EXISTS public."CourseSkills"
    ADD CONSTRAINT "FK_CourseSkills_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CourseSkills_CourseId"
    ON public."CourseSkills"("CourseId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Categories_CategoryId" FOREIGN KEY ("CategoryId")
    REFERENCES public."Categories" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_CategoryId"
    ON public."Courses"("CategoryId");


ALTER TABLE IF EXISTS public."Courses"
    ADD CONSTRAINT "FK_Courses_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Courses_SellerId"
    ON public."Courses"("SellerId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_CourseId"
    ON public."Enrollments"("CourseId");


ALTER TABLE IF EXISTS public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Enrollments_BuyerId"
    ON public."Enrollments"("BuyerId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Favorites_CourseId"
    ON public."Favorites"("CourseId");


ALTER TABLE IF EXISTS public."Favorites"
    ADD CONSTRAINT "FK_Favorites_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Favorites_UserId"
    ON public."Favorites"("UserId");


ALTER TABLE IF EXISTS public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Users_SellerId" FOREIGN KEY ("SellerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Notifications_SellerId"
    ON public."Notifications"("SellerId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_CourseId"
    ON public."Reviews"("CourseId");


ALTER TABLE IF EXISTS public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Reviews_BuyerId"
    ON public."Reviews"("BuyerId");


ALTER TABLE IF EXISTS public."TargetLearners"
    ADD CONSTRAINT "FK_TargetLearners_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TargetLearners_CourseId"
    ON public."TargetLearners"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Courses_CourseId" FOREIGN KEY ("CourseId")
    REFERENCES public."Courses" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_CourseId"
    ON public."TransactionDetails"("CourseId");


ALTER TABLE IF EXISTS public."TransactionDetails"
    ADD CONSTRAINT "FK_TransactionDetails_Transactions_TransactionId" FOREIGN KEY ("TransactionId")
    REFERENCES public."Transactions" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_TransactionDetails_TransactionId"
    ON public."TransactionDetails"("TransactionId");


ALTER TABLE IF EXISTS public."Transactions"
    ADD CONSTRAINT "FK_Transactions_Users_BuyerId" FOREIGN KEY ("BuyerId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Transactions_BuyerId"
    ON public."Transactions"("BuyerId");

END;

-- =============================================
-- DỮ LIỆU MẪU CHO TOÀN BỘ DATABASE
-- =============================================

-- 1. USERS
INSERT INTO public."Users" ("FullName", "Email", "PasswordHash", "Role", "CreatedAt", "RefreshToken", "RefreshTokenExpiryTime")
VALUES
-- ADMIN (1 người)
('Nguyễn Văn Sang', 'sang@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Admin', '2024-01-15 08:00:00+07', NULL, NULL),

-- SELLERS (5 người - Id: 2-6)
('Trần Thị Hương', 'huong.tran@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', '2024-02-10 09:30:00+07', NULL, NULL),
('Lê Minh Tuấn', 'tuan.le@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', '2024-02-15 10:15:00+07', NULL, NULL),
('Phạm Thu Hà', 'ha.pham@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', '2024-03-01 14:20:00+07', NULL, NULL),
('Hoàng Văn Nam', 'nam.hoang@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', '2024-03-10 11:00:00+07', NULL, NULL),
('Võ Thị Lan', 'lan.vo@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Seller', '2024-03-20 16:45:00+07', NULL, NULL),

-- BUYERS (10 người - Id: 7-16)
('Nguyễn Văn An', 'an.nguyen@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-01 08:30:00+07', NULL, NULL),
('Trần Thị Bình', 'binh.tran@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-05 09:00:00+07', NULL, NULL),
('Lê Văn Cường', 'cuong.le@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-10 10:30:00+07', NULL, NULL),
('Phạm Thị Dung', 'dung.pham@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-15 13:20:00+07', NULL, NULL),
('Hoàng Văn Em', 'em.hoang@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-20 15:00:00+07', NULL, NULL),
('Võ Thị Fân', 'fan.vo@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-04-25 11:45:00+07', NULL, NULL),
('Đặng Văn Giang', 'giang.dang@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-05-01 09:15:00+07', NULL, NULL),
('Bùi Thị Hoa', 'hoa.bui@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-05-05 14:30:00+07', NULL, NULL),
('Ngô Văn Ích', 'ich.ngo@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-05-10 10:00:00+07', NULL, NULL),
('Dương Thị Kim', 'kim.duong@gmail.com', 'Y6IE4cbribo1c2b2aq4IJg==.VJbIsl4pg2TOL3ZL4Xf2Pneez/s756/dq6ej15kjDPc=', 'Buyer', '2024-05-15 16:20:00+07', NULL, NULL);


-- 2. CATEGORIES
INSERT INTO public."Categories" ("Name")
VALUES
('Lập trình Web'),
('Lập trình Mobile'),
('Data Science'),
('Thiết kế đồ họa'),
('Marketing'),
('Kinh doanh'),
('Ngoại ngữ'),
('Nhiếp ảnh');


-- 3. COURSES
INSERT INTO public."Courses" ("Title", "Description", "Price", "Level", "TeacherName", "ImageUrl", "DurationHours", "TotalPurchased", "AverageRating", "CreatedAt", "UpdatedAt", "SellerId", "CategoryId", "IsApproved")
VALUES
-- Seller 2: Trần Thị Hương (3 khóa)
('Khóa học React JS từ cơ bản đến nâng cao', 'Học React JS toàn diện với các dự án thực tế. Từ JSX, Components, Hooks đến Redux và React Router.', 1500000, 'Beginner', 'Trần Thị Hương', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee', 40, 150, 4.5, '2024-03-01 10:00:00+07', '2024-05-20 14:30:00+07', 2, 1, true),
('Thiết kế UI/UX với Figma', 'Khóa học thiết kế giao diện chuyên nghiệp với Figma. Từ wireframe đến prototype hoàn chỉnh.', 1200000, 'Intermediate', 'Trần Thị Hương', 'https://images.unsplash.com/photo-1561070791-2526d30994b5', 30, 85, 4.7, '2024-03-15 11:00:00+07', '2024-06-01 09:15:00+07', 2, 4, true),
('Adobe Photoshop cho người mới bắt đầu', 'Làm chủ Photoshop với các kỹ thuật chỉnh sửa ảnh, thiết kế banner, poster chuyên nghiệp.', 900000, 'Beginner', 'Trần Thị Hương', 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea', 25, 120, 4.3, '2024-04-01 13:00:00+07', '2024-06-10 10:00:00+07', 2, 4, true),

-- Seller 3: Lê Minh Tuấn (3 khóa)
('Python cho Data Science', 'Khóa học Python chuyên sâu về phân tích dữ liệu với Pandas, NumPy, Matplotlib và Scikit-learn.', 2000000, 'Intermediate', 'Lê Minh Tuấn', 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935', 50, 200, 4.8, '2024-03-05 09:00:00+07', '2024-06-15 15:00:00+07', 3, 3, true),
('Machine Learning từ A-Z', 'Học Machine Learning thực chiến với TensorFlow và Keras. Xây dựng các mô hình AI thực tế.', 2500000, 'Advanced', 'Lê Minh Tuấn', 'https://images.unsplash.com/photo-1555949963-aa79dcee981c', 60, 95, 4.9, '2024-03-20 10:30:00+07', '2024-06-20 11:00:00+07', 3, 3, true),
('SQL và Database cho Data Analyst', 'Làm chủ SQL với PostgreSQL, MySQL. Từ query cơ bản đến tối ưu hiệu suất database.', 1300000, 'Beginner', 'Lê Minh Tuấn', 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d', 35, 110, 4.6, '2024-04-10 14:00:00+07', '2024-06-25 12:00:00+07', 3, 3, true),

-- Seller 4: Phạm Thu Hà (2 khóa)
('Flutter - Xây dựng ứng dụng di động đa nền tảng', 'Học Flutter và Dart để tạo app iOS và Android từ một mã nguồn duy nhất.', 1800000, 'Intermediate', 'Phạm Thu Hà', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c', 45, 130, 4.6, '2024-03-25 15:00:00+07', '2024-06-28 16:00:00+07', 4, 2, true),
('React Native - Lập trình Mobile hiện đại', 'Tạo ứng dụng mobile với React Native, kết nối API, xử lý state với Redux.', 1600000, 'Intermediate', 'Phạm Thu Hà', 'https://images.unsplash.com/photo-1551650975-87deedd944c3', 40, 90, 4.4, '2024-04-05 10:00:00+07', '2024-07-01 10:30:00+07', 4, 2, true),

-- Seller 5: Hoàng Văn Nam (3 khóa)
('Digital Marketing toàn diện 2024', 'Chiến lược marketing online: SEO, Google Ads, Facebook Ads, Email Marketing.', 1400000, 'Beginner', 'Hoàng Văn Nam', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f', 35, 175, 4.7, '2024-03-10 11:00:00+07', '2024-07-05 14:00:00+07', 5, 5, true),
('Facebook Ads Mastery', 'Làm chủ Facebook Ads từ thiết lập chiến dịch đến tối ưu chuyển đổi và scaling.', 1100000, 'Intermediate', 'Hoàng Văn Nam', 'https://images.unsplash.com/photo-1611162617474-5b21e879e113', 25, 140, 4.5, '2024-04-15 12:00:00+07', '2024-07-10 09:00:00+07', 5, 5, true),
('Khởi nghiệp và quản lý doanh nghiệp nhỏ', 'Hướng dẫn khởi nghiệp từ ý tưởng đến vận hành. Kế hoạch kinh doanh, tài chính, marketing.', 1000000, 'Beginner', 'Hoàng Văn Nam', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40', 30, 105, 4.4, '2024-04-20 13:30:00+07', '2024-07-12 10:00:00+07', 5, 6, true),

-- Seller 6: Võ Thị Lan (2 khóa)
('Tiếng Anh giao tiếp cho người đi làm', 'Nâng cao kỹ năng tiếng Anh giao tiếp trong môi trường công việc chuyên nghiệp.', 800000, 'Beginner', 'Võ Thị Lan', 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d', 40, 220, 4.6, '2024-03-28 09:00:00+07', '2024-07-15 11:00:00+07', 6, 7, true),
('Nhiếp ảnh cơ bản - Chụp ảnh đẹp với smartphone', 'Học cách chụp ảnh đẹp, composition, ánh sáng và editing với điện thoại.', 600000, 'Beginner', 'Võ Thị Lan', 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d', 20, 160, 4.5, '2024-04-25 14:00:00+07', '2024-07-18 15:00:00+07', 6, 8, true);


-- 4. COURSE CONTENTS
INSERT INTO public."CourseContents" ("Title", "Description", "CourseId")
VALUES
-- Course 1: React JS (CourseId: 1)
('Giới thiệu về React và môi trường phát triển', 'Cài đặt Node.js, npm, create-react-app. Tổng quan về React và ecosystem.', 1),
('JSX và Components', 'Làm việc với JSX syntax, tạo functional và class components.', 1),
('State và Props', 'Quản lý state trong component, truyền props giữa các components.', 1),
('React Hooks', 'useState, useEffect, useContext và custom hooks.', 1),
('React Router', 'Điều hướng trong React app với React Router v6.', 1),
('Redux và State Management', 'Quản lý state toàn cục với Redux Toolkit.', 1),

-- Course 2: UI/UX Figma (CourseId: 2)
('Giới thiệu Figma và giao diện', 'Làm quen với Figma, các công cụ cơ bản.', 2),
('Wireframing và Prototyping', 'Tạo wireframe và prototype tương tác.', 2),
('Design System', 'Xây dựng design system với components, styles, typography.', 2),
('Responsive Design', 'Thiết kế giao diện responsive cho các thiết bị.', 2),

-- Course 3: Photoshop (CourseId: 3)
('Làm quen với Photoshop', 'Giao diện, layers, công cụ cơ bản.', 3),
('Chỉnh sửa và retouching ảnh', 'Các kỹ thuật chỉnh màu, làm mịn da, xóa vật thể.', 3),
('Thiết kế banner và poster', 'Typography, composition, color theory.', 3),

-- Course 4: Python Data Science (CourseId: 4)
('Python cơ bản', 'Syntax, data types, functions, OOP.', 4),
('NumPy và Pandas', 'Xử lý mảng và dataframe, data cleaning.', 4),
('Data Visualization', 'Matplotlib, Seaborn - trực quan hóa dữ liệu.', 4),
('Machine Learning cơ bản', 'Scikit-learn, linear regression, classification.', 4),

-- Course 5: Machine Learning (CourseId: 5)
('Toán học cho Machine Learning', 'Linear Algebra, Calculus, Probability.', 5),
('Supervised Learning', 'Regression, Classification algorithms.', 5),
('Unsupervised Learning', 'Clustering, Dimensionality Reduction.', 5),
('Deep Learning với TensorFlow', 'Neural Networks, CNN, RNN.', 5),

-- Course 6: SQL Database (CourseId: 6)
('SQL cơ bản', 'SELECT, WHERE, JOIN, GROUP BY.', 6),
('Database Design', 'Normalization, relationships, indexes.', 6),
('Advanced SQL', 'Subqueries, CTEs, window functions.', 6),

-- Course 7: Flutter (CourseId: 7)
('Dart Programming', 'Dart syntax, OOP trong Dart.', 7),
('Flutter Widgets', 'Stateless, Stateful widgets, layouts.', 7),
('State Management', 'Provider, Riverpod, Bloc pattern.', 7),
('API Integration', 'HTTP requests, JSON parsing.', 7),

-- Course 8: React Native (CourseId: 8)
('React Native Setup', 'Cài đặt môi trường Android và iOS.', 8),
('Components và Navigation', 'React Navigation, Stack, Tab navigation.', 8),
('State Management với Redux', 'Redux trong React Native.', 8),

-- Course 9: Digital Marketing (CourseId: 9)
('Tổng quan Digital Marketing', 'Các kênh marketing online.', 9),
('SEO - Search Engine Optimization', 'On-page, off-page SEO.', 9),
('Google Ads', 'Search, Display, Shopping campaigns.', 9),
('Facebook Marketing', 'Facebook Ads, fanpage management.', 9),

-- Course 10: Facebook Ads (CourseId: 10)
('Facebook Ads cơ bản', 'Campaign structure, ad formats.', 10),
('Targeting và Audience', 'Custom audience, lookalike audience.', 10),
('Optimization và Scaling', 'A/B testing, budget optimization.', 10),

-- Course 11: Khởi nghiệp (CourseId: 11)
('Ý tưởng khởi nghiệp', 'Tìm ý tưởng, validate market.', 11),
('Kế hoạch kinh doanh', 'Business model canvas, financial planning.', 11),
('Marketing cho startup', 'Growth hacking, customer acquisition.', 11),

-- Course 12: Tiếng Anh giao tiếp (CourseId: 12)
('English for Meetings', 'Vocabulary và phrases cho họp.', 12),
('Email Writing', 'Viết email chuyên nghiệp.', 12),
('Presentation Skills', 'Thuyết trình bằng tiếng Anh.', 12),

-- Course 13: Nhiếp ảnh (CourseId: 13)
('Composition cơ bản', 'Rule of thirds, leading lines, framing.', 13),
('Ánh sáng trong nhiếp ảnh', 'Natural light, golden hour.', 13),
('Mobile Photography Editing', 'Snapseed, Lightroom mobile.', 13);


-- 5. COURSE SKILLS
INSERT INTO public."CourseSkills" ("Name", "CourseId")
VALUES
-- Course 1: React JS
('React.js', 1), ('JavaScript ES6+', 1), ('Redux', 1), ('React Hooks', 1),
-- Course 2: Figma
('Figma', 2), ('UI Design', 2), ('Prototyping', 2), ('Design System', 2),
-- Course 3: Photoshop
('Adobe Photoshop', 3), ('Photo Editing', 3), ('Graphic Design', 3),
-- Course 4: Python DS
('Python', 4), ('Pandas', 4), ('NumPy', 4), ('Data Analysis', 4),
-- Course 5: ML
('Machine Learning', 5), ('TensorFlow', 5), ('Deep Learning', 5), ('Python', 5),
-- Course 6: SQL
('SQL', 6), ('PostgreSQL', 6), ('Database Design', 6),
-- Course 7: Flutter
('Flutter', 7), ('Dart', 7), ('Mobile Development', 7),
-- Course 8: React Native
('React Native', 8), ('JavaScript', 8), ('Mobile Development', 8),
-- Course 9: Digital Marketing
('SEO', 9), ('Google Ads', 9), ('Facebook Ads', 9), ('Content Marketing', 9),
-- Course 10: FB Ads
('Facebook Ads', 10), ('Social Media Marketing', 10), ('Ad Optimization', 10),
-- Course 11: Startup
('Business Planning', 11), ('Entrepreneurship', 11), ('Marketing', 11),
-- Course 12: English
('English Communication', 12), ('Business English', 12), ('Presentation', 12),
-- Course 13: Photography
('Photography', 13), ('Mobile Photography', 13), ('Photo Editing', 13);


-- 6. TARGET LEARNERS
INSERT INTO public."TargetLearners" ("Description", "CourseId")
VALUES
-- Course 1
('Người mới bắt đầu học lập trình web', 1),
('Lập trình viên muốn chuyển sang React', 1),
('Sinh viên IT muốn học framework hiện đại', 1),
-- Course 2
('Designer muốn chuyển sang UI/UX', 2),
('Product Manager cần hiểu về design', 2),
-- Course 3
('Người mới bắt đầu học thiết kế đồ họa', 3),
('Marketer cần kỹ năng chỉnh sửa ảnh', 3),
-- Course 4
('Người muốn chuyển sang Data Science', 4),
('Analyst cần nâng cao kỹ năng Python', 4),
-- Course 5
('Data Scientist muốn học Deep Learning', 5),
('Lập trình viên muốn làm về AI', 5),
-- Course 6
('Người mới học về database', 6),
('Developer cần nâng cao SQL', 6),
-- Course 7
('Mobile developer muốn học Flutter', 7),
('Lập trình viên web chuyển sang mobile', 7),
-- Course 8
('Developer biết React muốn làm mobile', 8),
('Lập trình viên muốn học React Native', 8),
-- Course 9
('Người mới bắt đầu học marketing', 9),
('Chủ doanh nghiệp nhỏ', 9),
-- Course 10
('Marketer muốn chuyên sâu Facebook Ads', 10),
('Agency owner cần tối ưu chiến dịch', 10),
-- Course 11
('Người muốn khởi nghiệp', 11),
('Chủ doanh nghiệp startup', 11),
-- Course 12
('Nhân viên văn phòng', 12),
('Người cần tiếng Anh trong công việc', 12),
-- Course 13
('Người yêu thích nhiếp ảnh', 13),
('Content creator cần kỹ năng chụp ảnh', 13);


-- 7. TRANSACTIONS
INSERT INTO public."Transactions" ("TransactionCode", "PaymentMethod", "TotalAmount", "CreatedAt", "UpdatedAt", "BuyerId")
VALUES
-- Buyer 7: Nguyễn Văn An
('TXN2024050001', 'MoMo', 1500000, '2024-05-01 10:30:00+07', '2024-05-01 10:31:00+07', 7),
('TXN2024051501', 'VNPay', 2000000, '2024-05-15 14:20:00+07', '2024-05-15 14:21:00+07', 7),
-- Buyer 8: Trần Thị Bình
('TXN2024050501', 'Banking', 1200000, '2024-05-05 11:00:00+07', '2024-05-05 11:01:00+07', 8),
('TXN2024052001', 'MoMo', 1800000, '2024-05-20 09:30:00+07', '2024-05-20 09:31:00+07', 8),
-- Buyer 9: Lê Văn Cường
('TXN2024051001', 'VNPay', 900000, '2024-05-10 15:45:00+07', '2024-05-10 15:46:00+07', 9),
('TXN2024052501', 'Banking', 2500000, '2024-05-25 16:00:00+07', '2024-05-25 16:01:00+07', 9),
-- Buyer 10: Phạm Thị Dung
('TXN2024051201', 'MoMo', 1400000, '2024-05-12 10:15:00+07', '2024-05-12 10:16:00+07', 10),
-- Buyer 11: Hoàng Văn Em
('TXN2024051801', 'VNPay', 1600000, '2024-05-18 13:30:00+07', '2024-05-18 13:31:00+07', 11),
-- Buyer 12: Võ Thị Fân
('TXN2024052201', 'Banking', 800000, '2024-05-22 11:45:00+07', '2024-05-22 11:46:00+07', 12),
-- Buyer 13: Đặng Văn Giang
('TXN2024052801', 'MoMo', 1300000, '2024-05-28 14:00:00+07', '2024-05-28 14:01:00+07', 13);


-- 8. TRANSACTION DETAILS
INSERT INTO public."TransactionDetails" ("Price", "TransactionId", "CourseId")
VALUES
-- Transaction 1: Buyer 7 mua Course 1
(1500000, 1, 1),
-- Transaction 2: Buyer 7 mua Course 4
(2000000, 2, 4),
-- Transaction 3: Buyer 8 mua Course 2
(1200000, 3, 2),
-- Transaction 4: Buyer 8 mua Course 7
(1800000, 4, 7),
-- Transaction 5: Buyer 9 mua Course 3
(900000, 5, 3),
-- Transaction 6: Buyer 9 mua Course 5
(2500000, 6, 5),
-- Transaction 7: Buyer 10 mua Course 9
(1400000, 7, 9),
-- Transaction 8: Buyer 11 mua Course 8
(1600000, 8, 8),
-- Transaction 9: Buyer 12 mua Course 12
(800000, 9, 12),
-- Transaction 10: Buyer 13 mua Course 6
(1300000, 10, 6);


-- 9. ENROLLMENTS
INSERT INTO public."Enrollments" ("EnrollAt", "BuyerId", "CourseId")
VALUES
-- Buyer 7: 2 courses
('2024-05-01 10:31:00+07', 7, 1),
('2024-05-15 14:21:00+07', 7, 4),
-- Buyer 8: 2 courses
('2024-05-05 11:01:00+07', 8, 2),
('2024-05-20 09:31:00+07', 8, 7),
-- Buyer 9: 2 courses
('2024-05-10 15:46:00+07', 9, 3),
('2024-05-25 16:01:00+07', 9, 5),
-- Buyer 10: 1 course
('2024-05-12 10:16:00+07', 10, 9),
-- Buyer 11: 1 course
('2024-05-18 13:31:00+07', 11, 8),
-- Buyer 12: 1 course
('2024-05-22 11:46:00+07', 12, 12),
-- Buyer 13: 1 course
('2024-05-28 14:01:00+07', 13, 6);


-- 10. REVIEWS
INSERT INTO public."Reviews" ("Star", "CreatedAt", "Comment", "BuyerId", "CourseId")
VALUES
-- Course 1: React JS (3 reviews)
(5, '2024-05-03 10:00:00+07', 'Khóa học rất chi tiết và dễ hiểu. Giảng viên nhiệt tình, code demo rất thực tế. Recommend!', 7, 1),
(4, '2024-05-10 14:30:00+07', 'Nội dung tốt nhưng hơi nhanh ở phần Redux. Nhìn chung rất đáng học.', 14, 1),
(5, '2024-05-18 09:15:00+07', 'Best React course! Từ zero đến có thể làm project thực tế.', 15, 1),

-- Course 2: UI/UX Figma (2 reviews)
(5, '2024-05-07 11:20:00+07', 'Học xong tự tin thiết kế UI/UX chuyên nghiệp. Cô Hương dạy rất tâm huyết.', 8, 2),
(4, '2024-05-22 16:00:00+07', 'Khóa học hay, design system rất hữu ích cho công việc.', 16, 2),

-- Course 3: Photoshop (3 reviews)
(4, '2024-05-12 13:00:00+07', 'Phù hợp người mới. Các bài tập thực hành rất hay.', 9, 3),
(5, '2024-05-20 10:30:00+07', 'Sau khóa học edit ảnh đã pro hơn nhiều. Thanks cô!', 7, 3),
(4, '2024-05-25 15:00:00+07', 'Nội dung dễ hiểu, giảng viên nhiệt tình support.', 14, 3),

-- Course 4: Python Data Science (4 reviews)
(5, '2024-05-17 12:00:00+07', 'Khóa học Python hay nhất từng học. Pandas và visualization rất chi tiết.', 7, 4),
(5, '2024-05-23 14:30:00+07', 'Thầy Tuấn giảng rất dễ hiểu. Project cuối khóa rất thực tế.', 8, 4),
(4, '2024-05-28 11:00:00+07', 'Nội dung chất lượng, đáng đồng tiền bát gạo.', 15, 4),
(5, '2024-06-02 09:30:00+07', 'Học xong apply vào công việc ngay được. Highly recommended!', 16, 4),

-- Course 5: Machine Learning (3 reviews)
(5, '2024-05-27 16:30:00+07', 'Khóa ML tốt nhất. Từ lý thuyết đến thực hành đều chi tiết.', 9, 5),
(5, '2024-06-01 10:00:00+07', 'Deep learning phần rất hay. TensorFlow giảng dễ hiểu.', 10, 5),
(4, '2024-06-05 14:00:00+07', 'Nội dung advanced nhưng thầy giảng rất dễ hiểu.', 11, 5),

-- Course 6: SQL Database (2 reviews)
(5, '2024-05-30 11:30:00+07', 'SQL từ basic đến advanced. Học xong tự tin query phức tạp.', 13, 6),
(4, '2024-06-03 15:30:00+07', 'Khóa học hay, database design rất bổ ích.', 12, 6),

-- Course 7: Flutter (3 reviews)
(5, '2024-05-22 13:00:00+07', 'Flutter course tuyệt vời. Build được app hoàn chỉnh sau khóa học.', 8, 7),
(4, '2024-05-28 10:30:00+07', 'Dart và Flutter widgets giảng rất kỹ. Recommend cho ai muốn làm mobile.', 9, 7),
(5, '2024-06-04 16:00:00+07', 'Cô Hà dạy rất nhiệt tình. State management phần rất hay.', 14, 7),

-- Course 8: React Native (2 reviews)
(4, '2024-05-20 14:00:00+07', 'Học xong build được app React Native. Setup hơi khó nhưng sau đó ok.', 11, 8),
(5, '2024-05-26 11:30:00+07', 'Biết React rồi học RN rất dễ. Khóa học rất practical.', 15, 8),

-- Course 9: Digital Marketing (3 reviews)
(5, '2024-05-14 12:30:00+07', 'Khóa marketing toàn diện nhất. SEO, Ads đều được cover đầy đủ.', 10, 9),
(4, '2024-05-21 09:00:00+07', 'Rất nhiều kiến thức thực tế. Apply vào business ngay được.', 12, 9),
(5, '2024-05-29 15:30:00+07', 'Thầy Nam dạy dễ hiểu, case study rất hay. Must-learn!', 16, 9),

-- Course 10: Facebook Ads (2 reviews)
(5, '2024-05-24 10:00:00+07', 'Sau khóa học chạy ads hiệu quả hơn rất nhiều. ROI tăng đáng kể.', 10, 10),
(4, '2024-06-01 13:00:00+07', 'Targeting và optimization rất chi tiết. Đáng học!', 13, 10),

-- Course 11: Khởi nghiệp (2 reviews)
(4, '2024-05-25 11:00:00+07', 'Khóa học hữu ích cho startup. Business plan phần rất thực tế.', 11, 11),
(5, '2024-06-02 14:30:00+07', 'Học được nhiều insight về khởi nghiệp. Thầy Nam chia sẻ rất chân thật.', 14, 11),

-- Course 12: Tiếng Anh (4 reviews)
(5, '2024-05-24 09:30:00+07', 'Tiếng Anh giao tiếp cải thiện rõ rệt. Vocabulary rất practical.', 12, 12),
(4, '2024-05-30 10:00:00+07', 'Phù hợp cho môi trường công sở. Email writing rất hay.', 7, 12),
(5, '2024-06-05 11:30:00+07', 'Cô Lan dạy rất tận tâm. Presentation skills cải thiện nhiều.', 9, 12),
(4, '2024-06-08 15:00:00+07', 'Nội dung thiết thực, dễ áp dụng vào công việc.', 15, 12),

-- Course 13: Nhiếp ảnh (3 reviews)
(5, '2024-05-26 14:00:00+07', 'Chụp ảnh đẹp hơn rất nhiều sau khóa học. Composition rất hay.', 8, 13),
(4, '2024-06-01 10:30:00+07', 'Khóa học ngắn gọn, đủ dùng. Editing với Snapseed rất practical.', 10, 13),
(5, '2024-06-06 13:00:00+07', 'Best photography course! Cô Lan dạy rất dễ hiểu.', 16, 13);


-- 11. FAVORITES
INSERT INTO public."Favorites" ("UserId", "CourseId")
VALUES
-- Buyer 7: saved 3 courses
(7, 2), (7, 5), (7, 9),
-- Buyer 8: saved 2 courses
(8, 1), (8, 10),
-- Buyer 9: saved 3 courses
(9, 4), (9, 7), (9, 11),
-- Buyer 10: saved 2 courses
(10, 6), (10, 8),
-- Buyer 11: saved 3 courses
(11, 2), (11, 3), (11, 12),
-- Buyer 12: saved 2 courses
(12, 1), (12, 13),
-- Buyer 13: saved 3 courses
(13, 4), (13, 9), (13, 10),
-- Buyer 14: saved 2 courses
(14, 5), (14, 7),
-- Buyer 15: saved 3 courses
(15, 2), (15, 6), (15, 11),
-- Buyer 16: saved 2 courses
(16, 3), (16, 8);


-- 12. CARTS
INSERT INTO public."Carts" ("UserId", "CreatedAt")
VALUES
(7, '2024-06-10 10:00:00+07'),
(8, '2024-06-10 11:00:00+07'),
(9, '2024-06-10 12:00:00+07'),
(10, '2024-06-10 13:00:00+07'),
(11, '2024-06-10 14:00:00+07');


-- 13. CART ITEMS
INSERT INTO public."CartItems" ("CartId", "CourseId")
VALUES
-- Cart 1 (User 7): 2 items
(1, 6), (1, 10),
-- Cart 2 (User 8): 1 item
(2, 11),
-- Cart 3 (User 9): 3 items
(3, 1), (3, 8), (3, 13),
-- Cart 4 (User 10): 2 items
(4, 3), (4, 7),
-- Cart 5 (User 11): 1 item
(5, 5);


-- 14. NOTIFICATIONS
INSERT INTO public."Notifications" ("Message", "CreatedAt", "IsRead", "SellerId")
VALUES
-- Seller 2: Trần Thị Hương
('Khóa học "Khóa học React JS từ cơ bản đến nâng cao" đã được Admin phê duyệt', '2024-03-01 15:00:00+07', true, 2),
('Bạn có đơn hàng mới cho khóa "Khóa học React JS từ cơ bản đến nâng cao"', '2024-05-01 10:31:00+07', true, 2),
('Khóa học "Thiết kế UI/UX với Figma" nhận được review 5 sao', '2024-05-07 11:25:00+07', true, 2),
('Bạn có đơn hàng mới cho khóa "Thiết kế UI/UX với Figma"', '2024-05-05 11:01:00+07', false, 2),

-- Seller 3: Lê Minh Tuấn
('Khóa học "Python cho Data Science" đã được Admin phê duyệt', '2024-03-05 10:00:00+07', true, 3),
('Bạn có đơn hàng mới cho khóa "Python cho Data Science"', '2024-05-15 14:21:00+07', true, 3),
('Khóa học "Machine Learning từ A-Z" nhận được review 5 sao', '2024-05-27 16:35:00+07', true, 3),
('Bạn có đơn hàng mới cho khóa "Machine Learning từ A-Z"', '2024-05-25 16:01:00+07', false, 3),

-- Seller 4: Phạm Thu Hà
('Khóa học "Flutter - Xây dựng ứng dụng di động đa nền tảng" đã được Admin phê duyệt', '2024-03-25 16:00:00+07', true, 4),
('Bạn có đơn hàng mới cho khóa "Flutter - Xây dựng ứng dụng di động đa nền tảng"', '2024-05-20 09:31:00+07', true, 4),
('Khóa học "React Native - Lập trình Mobile hiện đại" nhận được review 5 sao', '2024-05-26 11:35:00+07', false, 4),

-- Seller 5: Hoàng Văn Nam
('Khóa học "Digital Marketing toàn diện 2024" đã được Admin phê duyệt', '2024-03-10 12:00:00+07', true, 5),
('Bạn có đơn hàng mới cho khóa "Digital Marketing toàn diện 2024"', '2024-05-12 10:16:00+07', true, 5),
('Khóa học "Digital Marketing toàn diện 2024" nhận được review 5 sao', '2024-05-14 12:35:00+07', true, 5),
('Bạn có review mới cho khóa "Facebook Ads Mastery"', '2024-05-24 10:05:00+07', false, 5),

-- Seller 6: Võ Thị Lan
('Khóa học "Tiếng Anh giao tiếp cho người đi làm" đã được Admin phê duyệt', '2024-03-28 10:00:00+07', true, 6),
('Bạn có đơn hàng mới cho khóa "Tiếng Anh giao tiếp cho người đi làm"', '2024-05-22 11:46:00+07', true, 6),
('Khóa học "Tiếng Anh giao tiếp cho người đi làm" nhận được review 5 sao', '2024-05-24 09:35:00+07', true, 6),
('Khóa học "Nhiếp ảnh cơ bản - Chụp ảnh đẹp với smartphone" nhận được review 5 sao', '2024-05-26 14:05:00+07', false, 6);